msi_id                  = ""
vault_name              = ""
sku_name                = "standard"
key_permissions         = ["List", "Create", "Delete", "Get", "Purge", "Recover", "Update", "GetRotationPolicy", "SetRotationPolicy"]
secret_permissions      = ["Set"]
key_name                = ""
key_type                = "RSA"
key_ops                 = ["decrypt", "encrypt", "sign", "unwrapKey", "verify", "wrapKey"]
key_size                = 2048